name: Run MBSS

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-mbss:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "MBSS"
          git config --global user.email "mbss@beatforge.net"

      - name: Download latest MBSS release
        run: |
          $latestRelease = Invoke-RestMethod -Uri "https://api.github.com/repos/beat-forge/mbss/releases/latest"
          $downloadUrl = ($latestRelease.assets | Where-Object { $_.name -eq "mbss.exe" }).browser_download_url
          Invoke-WebRequest -Uri $downloadUrl -OutFile mbss.exe
        shell: pwsh

      - name: Run MBSS
        run: .\mbss.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MBSS_REPO_PATH: ${{ github.workspace }}